config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: 'home#index'

  # For the moment only BOARD mode is available, that's why we disable this
  # post '/gpio/mode', to: 'home#set_mode', as: 'gpio_set_mode'
  post '/gpio/pins', to: 'home#set_input_pin', as: 'gpio_set_input_pin'
  post '/gpio/hard_reset', to: 'home#hard_reset', as: 'gpio_hard_reset'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :initialize_tasks

  private

    def initialize_tasks
      @gpio = AppSettings::GPIO
      return if @gpio.nil?

      # Set GPIO mode
      @gpio.set_numbering :board
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :gpio_validation, except: [:index]

  def index

  end

  def set_input_pin
    @pin = "#{params[:pin]}".to_i
    @state = "#{params[:state]}".to_sym

    @gpio.setup @pin, :as => :output, :initialize => :low

    case @state
    when :low
      @gpio.set_low @pin
    when :high
      @gpio.set_high @pin
    when :clean_up
      @gpio.clean_up @pin
    else
      redirect_to root_url, status: :unprocessable_entity
      return
    end

    render :index
  end

  def hard_reset
    @gpio.reset
    redirect_to root_url
  end

  private

    def gpio_validation
      redirect_to root_url, status: :unprocessable_entity if @gpio.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1.center GPIO

.row
  .col.s12
    %h2= 'GPIO Output Pins'
  = form_tag gpio_set_input_pin_path, method: :post do
    .col.s6.m4
      = label_tag :pin, 'PIN'
      = number_field_tag :pin, @pin
    .col.s6.m4
      = label_tag :state, 'STATE'
      = select_tag :state, options_for_select(%w(high low clean_up), @state), class: 'browser-default'
    .col.s12.m4{style: 'margin-top: 24px;'}
      = button_tag class: 'btn blue', type: :submit do
        = 'Send'
.row
  .col.s12
    %h2= 'Hard Reset'
  .col.s12
    = link_to 'Reset now!', gpio_hard_reset_path, class: 'btn red', method: :post, data: { confirm: 'Reset?' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RPI GPIO Server
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav
      .nav-wrapper.container
        = link_to '#', class: 'brand-logo' do
          = 'RPi'
    .container
      = yield